name: Rust checks

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rustfmt:
    name: Check Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          rustup install 
          rustup component add rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: x86_64-unknown-linux-gnu

      - name: Check Rust formatting
        run: cargo fmt --all -- --check

  check-clippy:
    name: Check, Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Must happen /after/ the checkout step, to pick up the toolchain
      # from the `rust-toolchain.toml` file.
      - name: Install toolchain
        run: |
          rustup install 
          rustup component add clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: x86_64-unknown-linux-gnu

      - name: Cargo check
        run: cargo check --all-targets

      - name: Clippy
        run: |
          cargo clippy --all-targets
